version: '3.8'
name: disco
services:
    disco:
      container_name: disco
      image: fargeo/disco
      build:
        context: ..
        dockerfile: disco/Dockerfile
      command: run_arches
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/disco
        - ../arches_templating/:/web_root/arches_templating
        - ../afs/:/web_root/afs
        - cantaloupe-data-disco:/web_root/disco/disco/uploadedfiles
      env_file:
        - ./docker/env_file.env
      ports:
        - 8001:80
        - 5678:5678
      stdin_open: true
      tty: true
      labels:
        - traefik.http.routers.my-container.rule=Host(`disco.local`)
        - traefik.frontend.passHostHeader=true

    cantaloupe_disco:
      container_name: cantaloupe-disco
      image: uclalibrary/cantaloupe:5.0.3-0
      volumes:
        - cantaloupe-data-disco:/imageroot
      ports:
        - 8183:8182
      env_file:
        - ./docker/env_file.env

    disco-webpack:
      container_name: disco-webpack
      image: fargeo/disco-webpack
      build:
        context: ..
        dockerfile: disco/docker/webpack/Dockerfile
      command: run_webpack
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/disco
      env_file:
        - ./docker/webpack/env_file.env
      ports:
        - 8080:8080
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    cantaloupe-data-disco:
