version: '3.8'
name: disco
services:
    disco:
      container_name: disco
      image: fargeo/disco
      build:
        args:
          # These are not delivered from the env_file - they're from --build-arg arguments.
          ARCHES_TEMPLATING_HOST_DIR: ../arches-templating/
          ARCHES_FOR_SCIENCE_HOST_DIR: ../arches-for-science/
          ARCHES_CORE_HOST_DIR: ../arches/
        context: ..
        dockerfile: disco/Dockerfile
      command: run_arches
      volumes:
        # To change these variables, modify/add the .env file prior to launch - NOT env_file.env
        - ${ARCHES_CORE_HOST_DIR:-../arches/}:/web_root/arches
        - ./:/web_root/disco
        - ${ARCHES_TEMPLATING_HOST_DIR:-../arches-templating/}:/web_root/arches-templating
        - ${ARCHES_FOR_SCIENCE_HOST_DIR:-../arches-for-science/}:/web_root/arches-for-science
        - $HOME/.aws/:/root/.aws/

        - cantaloupe-data-disco:/web_root/disco/disco/uploadedfiles
      ports:
        - ${HOST_PROJECT_PORT:-8001}:80
        - ${HOST_PROJECT_DEBUG_PORT:-5678}:5678
      stdin_open: true
      env_file:
        - ./docker/env_file.env
      tty: true
      labels:
        - traefik.http.routers.my-container.rule=Host(`disco.local`)
        - traefik.frontend.passHostHeader=true

    cantaloupe_disco:
      container_name: cantaloupe-disco
      image: uclalibrary/cantaloupe:5.0.3-0
      volumes:
        - cantaloupe-data-disco:/imageroot
      ports:
        - 8183:8182
      env_file:
        - ./docker/env_file.env

    disco-webpack:
      container_name: disco-webpack
      image: fargeo/disco-webpack
      build:
        context: ..
        dockerfile: disco/docker/webpack/Dockerfile
      command: run_webpack
      volumes:
        - ../arches/:/web_root/arches
        - ./:/web_root/disco
        - ../arches-for-science/:/web_root/arches-for-science
      env_file:
        - ./docker/webpack/env_file.env
      ports:
        - 8080:8080
      stdin_open: true
      tty: true

networks:
  default:
    external: true
    name: arches7-0-dev

volumes:
    cantaloupe-data-disco:
